
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.RandomStringUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Shrishty
 */
public class IJFBooking extends javax.swing.JInternalFrame {

    /**
     * Creates new form IJFBooking
     */
    public IJFBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FldFare = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FldContact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FldL_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FldUserID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FldF_Name = new javax.swing.JTextField();
        FldGender = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        FldTicketID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFlight = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        FldTotal = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        CBArrival = new javax.swing.JComboBox<>();
        CBDeparture = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        FldCustomerID = new javax.swing.JTextField();
        FldSeats = new javax.swing.JTextField();
        BtnCalculate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1000, 750));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel2.setText("First Name");
        jLabel2.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel3.setText("Last Name");
        jLabel3.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel4.setText("NIC ID");
        jLabel4.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel5.setText("Gender");
        jLabel5.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel6.setText("Contact");
        jLabel6.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel7.setText("Arrival");
        jLabel7.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel8.setText("Departure");
        jLabel8.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel9.setText("Fare");
        jLabel9.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Book your Journey");

        btnGo.setBackground(new java.awt.Color(204, 204, 255));
        btnGo.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btnGo.setForeground(new java.awt.Color(51, 153, 0));
        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel10.setText("Ticket ID");

        FldTicketID.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel11.setText("Seats");
        jLabel11.setEnabled(false);

        btnBook.setBackground(new java.awt.Color(51, 51, 51));
        btnBook.setFont(new java.awt.Font("Yu Mincho Light", 1, 18)); // NOI18N
        btnBook.setForeground(new java.awt.Color(102, 255, 102));
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        TableFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight ID", "Flight Name", "Arrival", "Departure", "Date"
            }
        ));
        TableFlight.setColumnSelectionAllowed(true);
        TableFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableFlightMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableFlight);
        TableFlight.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel12.setText("Total Fair");
        jLabel12.setEnabled(false);

        btnCancel.setBackground(new java.awt.Color(51, 51, 51));
        btnCancel.setFont(new java.awt.Font("Yu Mincho Light", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        CBArrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chennai", "Goa", "Lucknow", "Kolkata", "Mumbai" }));

        CBDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chennai", "Goa", "Lucknow", "Kolkata", "Mumbai" }));

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel13.setText("Customer ID");

        BtnCalculate.setBackground(new java.awt.Color(0, 0, 0));
        BtnCalculate.setForeground(new java.awt.Color(204, 204, 255));
        BtnCalculate.setText("Calculate");
        BtnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalculateActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setForeground(new java.awt.Color(51, 255, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(btnGo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(705, 705, 705)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FldL_Name)
                                    .addComponent(FldContact)
                                    .addComponent(FldGender)
                                    .addComponent(FldFare)
                                    .addComponent(FldTotal)
                                    .addComponent(FldCustomerID)
                                    .addComponent(FldUserID)
                                    .addComponent(FldF_Name)
                                    .addComponent(FldSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(BtnCalculate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(btnSearch))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CBArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(88, 88, 88)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CBDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(FldTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(243, 243, 243)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(FldTicketID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FldCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearch)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(FldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FldF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FldL_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(FldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(FldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(FldFare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(FldSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(FldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCalculate))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
       try{
          Connection conc;
          PreparedStatement pre = null;
          int cc;
          String arrival = CBArrival.getSelectedItem().toString();
          String departure = CBDeparture.getSelectedItem().toString();
          
          try {
              Class.forName("com.mysql.jdbc.Driver");
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(IJFBooking.class.getName()).log(Level.SEVERE, null, ex);
          }
          conc= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/air_line","root","munchy");
          java.sql.Statement s = conc.createStatement();
          pre =conc.prepareStatement("select * from flight where Arrival=? && Departure=?");
          pre.setString(1,arrival);
          pre.setString(2,departure);
          ResultSet rs;
          rs = pre.executeQuery();
          ResultSetMetaData RSMD = rs.getMetaData();
           cc = RSMD.getColumnCount();
           DefaultTableModel DFT = (DefaultTableModel)TableFlight.getModel();
           DFT.setRowCount(0);
           while(rs.next()){
               Vector v2 = new Vector();
               for(int i=1; i <= cc; i++){
                   v2.add(rs.getString("Flight_ID"));
                   v2.add(rs.getString("Flight_Name"));
                   v2.add(rs.getString("Arrival"));
                   v2.add(rs.getString("Departure"));
                   v2.add(rs.getString("Date"));
               }
               DFT.addRow(v2);
           }
        }
        catch(SQLException ex){  
            System.out.println(ex);
           Logger.getLogger(IJFBooking.class.getName(), title).log(Level.SEVERE,null,ex); 
        }
        
    }//GEN-LAST:event_btnGoActionPerformed

    private void TableFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableFlightMouseClicked
        try{
            Connection conc;
            PreparedStatement pre = null;
            int row = TableFlight.getSelectedRow();
            String id = TableFlight.getModel().getValueAt(row, 0).toString();
            String dep = TableFlight.getModel().getValueAt(row, 3).toString();
            conc= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/air_line","root","munchy");
            java.sql.Statement s = conc.createStatement();
            pre =conc.prepareStatement("select * from flight where Flight_ID=? && Departure=?");
            pre.setString(1,id);
            pre.setString(2,dep);
            ResultSet rs = pre.executeQuery();
            rs.next();
            FldFare.setText(rs.getString("Fare"));
            
        }
        catch(SQLException ex){ 
            System.out.println(ex);
           Logger.getLogger(IJFBooking.class.getName(), title).log(Level.SEVERE,null,ex); 
        }
        
    }//GEN-LAST:event_TableFlightMouseClicked

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        try{
         String arrival = CBArrival.getSelectedItem().toString();
         String departure = CBDeparture.getSelectedItem().toString();
         String CustID = FldCustomerID.getText();
         
         int column = 0;
         int row = TableFlight.getSelectedRow();
         String flightID = TableFlight.getModel().getValueAt(row,column).toString();
         String ticketID = FldTicketID.getText();
         String seats = FldSeats.getText();
         column = 4;
         row = TableFlight.getSelectedRow();
         String date = TableFlight.getModel().getValueAt(row, column).toString();
         String totalAmount = FldTotal.getText();
         
         
         Connection conc;
         PreparedStatement pre;
       
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IJFBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            conc = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/air_line","root","munchy");
            pre = conc.prepareStatement("insert into Ticket(Ticket_ID,Customer_ID,Flight_ID,Arrival,Departure,Date,Seats,TotalAmount)values(?,?,?,?,?,?,?,?)");
       
            pre.setString(1, ticketID );
            pre.setString(2, flightID );
            pre.setString(3, CustID);
            pre.setString(4, arrival);
            pre.setString(5, departure);
            pre.setString(6, date);
            pre.setString(7, seats);
            pre.setString(8, totalAmount);   
            pre.executeUpdate();
            JOptionPane.showMessageDialog(null, "Flight Booked");
        } 
        catch(SQLException ex){ 
           System.out.println(ex);
          Logger.getLogger(AddCustomer.class.getName(), title).log(Level.SEVERE,null,ex); 
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void BtnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalculateActionPerformed
        int s = Integer.parseInt(FldSeats.getText());
        int f = Integer.parseInt(FldFare.getText());
        int t = s*f;
        FldTotal.setText(t + "");
        
        int length = 10;
        boolean useLetters = true;
        boolean useNumbers = true;
        String ticketId = RandomStringUtils.random(length, useLetters, useNumbers);
        FldTicketID.setText(ticketId);
        
    }//GEN-LAST:event_BtnCalculateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
          this.hide();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        Connection conc;
        PreparedStatement pre;
        try{
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IJFBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            conc = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/air_line","root","munchy");
            String sql = "SELECT Customer_ID,NIC_ID,First_Name,Last_Name,Contact_No,Gender FROM customer WHERE Customer_ID=?";
            pre =conc.prepareStatement(sql);
            pre.setString(1,FldCustomerID.getText());

            ResultSet rs = pre.executeQuery();
            while(rs.next()) { 
            FldCustomerID.setText(rs.getString("Customer_ID"));
            FldUserID.setText(rs.getString("NIC_ID"));
            FldF_Name.setText(rs.getString("First_Name"));
            FldL_Name.setText(rs.getString("Last_Name"));
            FldContact.setText(rs.getString("Contact_No"));
            FldGender.setText(rs.getString("Gender"));
            }
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalculate;
    private javax.swing.JComboBox<String> CBArrival;
    private javax.swing.JComboBox<String> CBDeparture;
    private javax.swing.JTextField FldContact;
    private javax.swing.JTextField FldCustomerID;
    private javax.swing.JTextField FldF_Name;
    private javax.swing.JTextField FldFare;
    private javax.swing.JTextField FldGender;
    private javax.swing.JTextField FldL_Name;
    private javax.swing.JTextField FldSeats;
    private javax.swing.JTextField FldTicketID;
    private javax.swing.JTextField FldTotal;
    private javax.swing.JTextField FldUserID;
    private javax.swing.JTable TableFlight;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private String toString(int total, int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
