
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shrishty
 */
public class JFfirst extends javax.swing.JFrame {

    /**
     * Creates new form JFfirst
     */
    public JFfirst() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        DTopJFfirst = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenCustomer = new javax.swing.JMenu();
        MItmSearch = new javax.swing.JMenuItem();
        MenItmAdd = new javax.swing.JMenuItem();
        jMenFlight = new javax.swing.JMenu();
        MenItmBookFlight = new javax.swing.JMenuItem();
        MenItmAddFlight = new javax.swing.JMenuItem();
        jMenAdmin = new javax.swing.JMenu();
        MenItmUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFont(new java.awt.Font("Aldhabi", 1, 24)); // NOI18N
        setLocation(new java.awt.Point(100, 0));

        DTopJFfirst.setFocusable(false);
        DTopJFfirst.setPreferredSize(new java.awt.Dimension(1100, 800));

        javax.swing.GroupLayout DTopJFfirstLayout = new javax.swing.GroupLayout(DTopJFfirst);
        DTopJFfirst.setLayout(DTopJFfirstLayout);
        DTopJFfirstLayout.setHorizontalGroup(
            DTopJFfirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DTopJFfirstLayout.setVerticalGroup(
            DTopJFfirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("AR BERKLEY", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Aeolus Airlines");

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Yu Mincho Demibold", 0, 14)); // NOI18N
        jButton1.setText("Support");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jmenCustomer.setText("Customer");
        jmenCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenCustomerActionPerformed(evt);
            }
        });

        MItmSearch.setText("Search");
        MItmSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItmSearchActionPerformed(evt);
            }
        });
        jmenCustomer.add(MItmSearch);

        MenItmAdd.setText("Add");
        MenItmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenItmAddActionPerformed(evt);
            }
        });
        jmenCustomer.add(MenItmAdd);

        jMenuBar1.add(jmenCustomer);

        jMenFlight.setText("Flight/Ticket");

        MenItmBookFlight.setText("Book Flight");
        MenItmBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenItmBookFlightActionPerformed(evt);
            }
        });
        jMenFlight.add(MenItmBookFlight);

        MenItmAddFlight.setText("Add Flight");
        MenItmAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenItmAddFlightActionPerformed(evt);
            }
        });
        jMenFlight.add(MenItmAddFlight);

        jMenuBar1.add(jMenFlight);

        jMenAdmin.setText("Create Admin");

        MenItmUser.setText("Create User");
        MenItmUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenItmUserActionPerformed(evt);
            }
        });
        jMenAdmin.add(MenItmUser);

        jMenuBar1.add(jMenAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DTopJFfirst, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DTopJFfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenCustomerActionPerformed
       
    }//GEN-LAST:event_jmenCustomerActionPerformed

    private void MenItmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenItmAddActionPerformed

        try {
            AddCustomer IJFAddCustomer = new AddCustomer();
            IJFAddCustomer.setVisible(true);
            DTopJFfirst.add(IJFAddCustomer);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFfirst.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFfirst.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenItmAddActionPerformed

    private void MItmSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItmSearchActionPerformed
       IJFSearch search = new IJFSearch();
       search.setVisible(true);
       DTopJFfirst.add(search);
    }//GEN-LAST:event_MItmSearchActionPerformed

    private void MenItmBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenItmBookFlightActionPerformed
        IJFBooking booking = new IJFBooking();
        booking.setVisible(true);
        DTopJFfirst.add(booking);
    }//GEN-LAST:event_MenItmBookFlightActionPerformed

    private void MenItmAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenItmAddFlightActionPerformed
        IJFAddFlight addFlight = null;
        try {
            addFlight = new IJFAddFlight();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFfirst.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFfirst.class.getName()).log(Level.SEVERE, null, ex);
        }
        addFlight.setVisible(true);
        DTopJFfirst.add(addFlight);
    }//GEN-LAST:event_MenItmAddFlightActionPerformed

    private void MenItmUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenItmUserActionPerformed
      IJFAdmin adminWindow = null;
        try {
            adminWindow = new IJFAdmin();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFfirst.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFfirst.class.getName()).log(Level.SEVERE, null, ex);
        }
      adminWindow.setVisible(true);
      DTopJFfirst.add(adminWindow);
    }//GEN-LAST:event_MenItmUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Request queued\nFor more call 1000011");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFfirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFfirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFfirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFfirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JFfirst().setVisible(true);
                new LogginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DTopJFfirst;
    private javax.swing.JMenuItem MItmSearch;
    private javax.swing.JMenuItem MenItmAdd;
    private javax.swing.JMenuItem MenItmAddFlight;
    private javax.swing.JMenuItem MenItmBookFlight;
    private javax.swing.JMenuItem MenItmUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenAdmin;
    private javax.swing.JMenu jMenFlight;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JMenu jmenCustomer;
    // End of variables declaration//GEN-END:variables
}
